version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: memovoz-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: memovoz
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: memovoz-backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DATABASE_URL: postgresql://postgres:postgres123@db:5432/memovoz
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      JWT_SECRET: mi-secreto-super-seguro-12345
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - /app/node_modules

volumes:
  postgres_data: